import { useTheme } from "@mui/material";

export const styledItem = () => {
  const myTheme = useTheme();
  return {
    headStyle: {
      color: myTheme.palette.text.default,
      fontFamily: myTheme.typography.fontFamily,
      letterSpacing: "0px",
      fontSize: myTheme.typography.fontSize.extraMedium,
      fontWeight: myTheme.typography.fontWeight.medium,
      whiteSpace: "nowrap",
    },
    dataStyle: {
      color: myTheme.palette.text.default,
      fontSize: myTheme.typography.fontSize.medium,
      fontFamily: myTheme.typography.fontFamily,
      textAlign: "left",
      letterSpacing: "0px",
    },
    linkStyle: {
      color: myTheme.palette.secondary.main,
      textDecorationColor: myTheme.palette.secondary.main,
      cursor: "pointer",
      fontSize: myTheme.typography.fontSize.medium,
      textAlign: "left",
      fontFamily: myTheme.typography.fontFamily,
    },
    tableCellStyle: {
      borderColor: myTheme.palette.background.primary,
      bgcolor: myTheme.palette.background.primary,
    },
    parentGridStyle: {
      width: "100%",
      overflow: "hidden",
      marginTop: "1rem",
      borderRadius: "6px",
      border: "1px solid #E6E6E6",
      display: "inline-flex",
      backgroundColor: myTheme.palette.background.primary,
      flexDirection: "column",
      justifyContent: "space-between",
    },
    reminderBoxStyle: {
      display: "inline-block",
      padding: "4px 20px",
      borderRadius: "4px",
      cursor: "pointer",
    },
    reminderBoxStyle1: {
      display: "inline-block",
      padding: "4px 12px",
      borderRadius: "4px",
      cursor: "pointer",
    },
    reminderTextStyle: {
      color: myTheme.palette.background.primary,
      textAlign: "left",
      fontFamily: myTheme.typography.fontFamily,
      letterSpacing: "0px",
      fontSize: myTheme.typography.fontSize.small,
    },
    tablePagenationStyle: {
      background: myTheme.palette.background.primary,
      borderTop: "1px solid #E6E6E6",
    },
    tableContainerStyle: {
      height: "67.7vh",
      scrollbarWidth: "none",
      scrollBehavior: "smooth",
    },
    feedbackText: {
      fontFamily: myTheme.typography.fontFamily,
      fontSize: myTheme.typography.fontSize.large,
      textAlign: "left",
      color: myTheme.palette.text.default,
      fontWeight: myTheme.typography.fontWeight.medium,
    },
    filterBoxIcon: {
      ".MuiAvatar-img": { height: "1rem", width: "1rem" },
      backgroundColor: myTheme.palette.secondary.main,
      borderRadius: "4px",
      padding: "0px 4px",
      cursor: "pointer",
    },
    parentGridSignalStyle: {
      bgcolor: myTheme.palette.background.primary,
      border: "1px solid #E3E3E3",
      borderRadius: "4px",
      padding: "1rem ",
      marginTop: "24px",
    },
    parentGridSignalStyleWeb: {
      bgcolor: myTheme.palette.background.primary,
      border: "1px solid #E3E3E3",
      borderRadius: "4px",
      padding: "1rem ",
      marginTop: "24px",
      display: {
        xs: "none",
        sm: "block",
      },
    },
    parentGridSignalStyleMob: {
      bgcolor: myTheme.palette.background.primary,
      border: "1px solid #E3E3E3",
      borderRadius: "4px",
      padding: "1rem ",
      marginTop: "24px",
      display: {
        xs: "block",
        sm: "none",
      },
    },
    parentBoxSignalStyle: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      overflowX: "auto",
    },
    parentBoxSignalStyleMob: {
      display: "grid",
      justifyContent: "space-between",
      alignItems: "center",
      gridTemplateColumns: "1fr",
      gridTemplateAreas: `
      "signalhead addbutton " 
      "inputbox inputbox"
      `,
      gap: "1rem 0px",
    },
    headSignalStyle: {
      color: "#353448",
      fontSize: myTheme.typography.fontSize.medium,
      textAlign: "left",
      letterSpacing: "0px",
      fontFamily: myTheme.typography.fontFamily,
      fontWeight: "500",
    },
    headSignalStyleMob: {
      color: "#353448",
      fontSize: myTheme.typography.fontSize.medium,
      textAlign: "left",
      letterSpacing: "0px",
      fontFamily: myTheme.typography.fontFamily,
      fontWeight: "500",
      gridArea: "signalhead",
      whiteSpace: "nowrap",
    },
    paperSearchStyle: {
      border: "1px solid #CACACA",
      display: "flex",
      alignItems: "center",
      padding: "5px 10px",
      borderShadow: "none",
      width: "310px",
    },
    paperSearchStyleMob: {
      border: "1px solid #CACACA",
      display: "flex",
      alignItems: "center",
      padding: "5px 10px",
      gridArea: "inputbox",
    },
    searchIconStyle: { color: "#888888", width: "20px", height: "20px" },
    searchInputBarStyle: {
      fontSize: "0.875rem",
      fontFamily: myTheme.typography.fontFamily,
      textAlign: "left",
      letterSpacing: "0px",
      ml: 1,
    },
    signalButtonStyle: {
      textAlign: "left",
      fontSize: myTheme.typography.fontSize.medium,
      fontFamily: myTheme.typography.fontFamily,
      textTransform: "none",
      fontWeight: "300",
      bgcolor: myTheme.palette.secondary.main,
      padding: "3px 40px",
      color: myTheme.palette.background.primary,
    },
    signalButtonStyleMob: {
      textAlign: "left",
      fontSize: myTheme.typography.fontSize.medium,
      fontFamily: myTheme.typography.fontFamily,
      textTransform: "none",
      fontWeight: "300",
      bgcolor: myTheme.palette.secondary.main,
      padding: "3px 40px",
      color: myTheme.palette.background.primary,
      gridArea: "addbutton",
    },
    bodyActionIconStyle: {
      height: "28px",
      width: "28px",
      ".MuiAvatar-img": { height: "12px", width: "12px" },
      bgcolor: myTheme.palette.secondary.utlinedHover,
      cursor: "pointer",
    },
    tabsStyle: {
      background: myTheme.palette.background.default,
      padding: "24px",
    },
    editContentHeading: {
      color: myTheme.palette.text.label,
      display: "flex",
      columnGap: "2px",
      textAlign: "left",
      fontFamily: myTheme.typography.fontFamily,
      letterSpacing: "0px",
      fontSize: myTheme.typography.fontSize.verySmall,
    },
    editContentTextBox: {
      fontSize: myTheme.typography.fontSize.small,
      fontFamily: myTheme.typography.fontFamily,
      color: myTheme.palette.text.default,
      textAlign: "left",
      letterSpacing: "0px",
      border: "1px solid #EBEBEB",
      borderRadius: "4px",
      minHeight: "120px",
      padding: "9px 12px",
    },
    editContentHeadingMust: { color: myTheme.palette.text.danger },
    editContentBox: { paddingBottom: "1rem" },
    editContentGrid: { padding: "24px" },
    feedbackTypeBox: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: "4px",
      height: "109px",
      width: "119px",
      cursor: "pointer",
    },
    feedbackAvatarBox: { height: "28px", width: "28px", overflow: "visible" },
    feedbackInfoBox: { display: "flex", columnGap: "8px", marginTop: "12px" },
    feedbackTypeInfoText: {
      fontSize: myTheme.typography.fontSize.small,
      textAlign: "left",
      color: myTheme.palette.text.label,
      letterSpacing: "0px",
      fontFamily: myTheme.typography.fontFamily,
    },
    styledTabs: {
      "& .MuiTabs-indicator": {
        backgroundColor: myTheme.palette.primary.main,
        height: "3px",
        borderRadius: "2px 2px 0px 0px",
      },
    },
    styledDialogBox: {
      padding: "0.313rem 0.938rem",
      fontSize: myTheme.typography.fontSize.small,
      fontFamily: myTheme.typography.fontFamily,
      textTransform: "capitalize",
      fontWeight: myTheme.typography.fontWeight.medium,
      cursor: "pointer",
      borderRadius: "4px",
      lineHeight: 1.75,
    },
    styledDialogContent: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      padding: { sm: "50px 48px", xs: "40px 30px" },
      "@media (max-width: 325px)": {
        padding: "40px 16px",
      },
    },
    styledDialogContentBoxImage: {
      margin: " 0px 0px 24px 0px",
      height: "48px",
      width: "48px",
    },
    styledDialogContentBoxText: {
      textAlign: "center",
      maxWidth: "304px",
      color: myTheme.palette.text.default,
      fontSize: myTheme.typography.fontSize.medium,
      fontFamily: myTheme.typography.fontFamily,
    },
    styledDialogContentButtonBox: {
      display: "flex",
      justifyContent: "space-between",
      width: "-webkit-fill-available",
    },
    styledDialogContentCancelButton: {
      minWidth: { sm: "138px", xs: "100px" },
      "@media (min-width: 425px)": { minWidth: "138px" },
    },
  };
};
